heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy an elasticsearch cluster on the
  Elastx ops:IaaS.

parameter_groups:

- label: Server Settings
  parameters:
  - server_hostname_search
  - server_hostname_log
  - flavor_search
  - flavor_log
  - es_node_count

parameters:

  flavor_search:
    description: Elastx Cloud Server flavor for search node
    type: string
    default: m1.large
    constraints:
    - allowed_values:
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m1.2xlarge
      description: |
        Must be a valid Elastx Cloud Server flavor for the region you have
        selected to deploy into.

  flavor_log:
    description: Elastx Cloud Server flavor for log node
    type: string
    default: m1.xlarge
    constraints:
    - allowed_values:
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m1.2xlarge
      description: |
        Must be a valid Elastx Cloud Server flavor for the region you have
        selected to deploy into.

  server_hostname_search:
    description: Hostname for the servers
    type: string
    default: es-search

  server_hostname_log:
    description: Hostname for the servers
    type: string
    default: es-log

  es_node_count:
    description: Number of nodes to create
    type: number
    default: 2

  keyname:
    description: Name of an existing KeyPair to enable SSH access
    type: string

  imagename:
    description: Linux image name
    type: string
    default: centos-6.5-20140117.0

  public_net_id:
    type: string
    label: Public network ID
    description: ID of public network
    default: 62954df1-05bb-42e5-9960-ca921cccaeeb

  private_net_id:
    label: Private network ID
    type: string
    description: ID of private network into which servers get deployed
    default: 439d2ca2-d72b-43a9-876a-67cb4a6ad4a0

  private_subnet_id:
    label: Private subnet ID
    type: string
    description: ID of private sub network into which servers get deployed
    default: 9c77493c-93a2-458c-b4ea-1ccb2cd6a185


resources:

  LB-monitor:
      type: OS::Neutron::HealthMonitor
      properties:
        type: HTTP
        delay: 3
        max_retries: 5
        timeout: 10

  LB-pool:
      type: OS::Neutron::Pool
      properties:
        name: LB-pool
        protocol: TCP
        subnet_id: { get_param: private_subnet_id }
        lb_method: LEAST_CONNECTIONS
        monitors: [ { get_resource: LB-monitor } ]
        vip: {"protocol_port": 80}

  LB:
      type: OS::Neutron::LoadBalancer
      depends_on:
        - es_search_nodes
      properties:
        members:
        - addresses: { get_attr: [es_search_nodes, es_private_ip] }
        pool_id: { get_resource: LB-pool }
        protocol_port: 80

  es_search_nodes:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: es_node_count }
      resource_def:
        type: https://raw.githubusercontent.com/elastx/heat-templates/master/ElasticSearch/ElasticSearch_SearchNode.yaml
        properties:
          server_flavor:     { get_param: flavor_search }
          server_hostname:   { get_param: server_hostname_search }
          ssh_keypair_name:  { get_param: keyname }
          private_net_id:    { get_param: private_net_id }
          private_subnet_id: { get_param: private_subnet_id }
          imagename:         { get_param: imagename }

  es_log_nodes:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: 1
      resource_def:
        type: https://raw.githubusercontent.com/elastx/heat-templates/master/ElasticSearch/ElasticSearch_LogNode.yaml
        properties:
          server_flavor:     { get_param: flavor_log }
          server_hostname:   { get_param: server_hostname_log }
          ssh_keypair_name:  { get_param: keyname }
          private_net_id:    { get_param: private_net_id }
          private_subnet_id: { get_param: private_subnet_id }
          imagename:         { get_param: imagename }

outputs:

  es_search_server_ips:
    value: { get_attr: [es_search_nodes, es_server_ip] }
    description: "Elasticsearch search Server IPs"

  es_log_server_ips:
    value: { get_attr: [es_log_nodes, es_server_ip] }
    description: "Elasticsearch log Server IPs"
