heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running elasticsearch.

parameters:

  server_flavor:
    description: Flavor for Cloud Servers
    type: string

  server_hostname:
    description: Hostname for the server.
    type: string

  key_name:
    description: Nova keypair name for ssh access to the server
    type: string

  private_net_id:
    description: cloud network id for intra-cluster communication
    type: string

  image_name:
    description: Linux image name
    type: string

  security_group:
    description: Security groups
    type: string

resources:

  es_server:
    type: "OS::Nova::Server"
    properties:
      name:     { get_param: server_hostname }
      flavor:   { get_param: server_flavor }
      image:    { get_param: image_name }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: es_server_port }

  es_server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }
      security_groups: [{ get_param: security_group }]

  es_server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: es_server_port }

outputs:

  es_private_ip:
    value: { get_attr: [es_server, first_address] }

  es_private_ip_new:
    value: { get_attr: [es_server, networks, { get_param: private_net_id }, 0] }

  es_port_id:
    value: { get_resource: [es_server_port] }
