heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy an elasticsearch cluster on the
  Elastx ops:IaaS.

parameter_groups:

- label: Server Settings
  parameters:
  - server_hostname_search
  - server_hostname_log
  - flavor_search
  - flavor_log
  - es_node_count

parameters:

  flavor_search:
    description: Elastx Cloud Server flavor for search node
    type: string
    default: m1.large
    constraints:
    - allowed_values:
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m1.2xlarge
      description: |
        Must be a valid Elastx Cloud Server flavor for the region you have
        selected to deploy into.

  flavor_log:
    description: Elastx Cloud Server flavor for log node
    type: string
    default: m1.xlarge
    constraints:
    - allowed_values:
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m1.2xlarge
      description: |
        Must be a valid Elastx Cloud Server flavor for the region you have
        selected to deploy into.

  server_hostname_search:
    description: Hostname for the servers
    type: string
    default: es-search

  server_hostname_log:
    description: Hostname for the servers
    type: string
    default: es-log

  es_node_count:
    description: Number of nodes to create
    type: number
    default: 3

  keyname:
    description: Name of an existing KeyPair to enable SSH access
    type: string

  imagename:
    description: Linux image name
    type: string
    default: centos-6.5-20140117.0


resources:

  LB-monitor:
      type: OS::Neutron::HealthMonitor
      properties:
        type: PING
        delay: 3
        max_retries: 5
        timeout: 10

  LB-pool:
      type: OS::Neutron::Pool
      properties:
        name: LB-pool
        protocol: TCP
        subnet_id: { get_param: private_subnet_id }
        lb_method: LEAST_CONNECTIONS
        monitors: [ { get_resource: LB-monitor } ]
        vip: {"address": 192.168.23.200, "protocol_port": 80}

  LB:
      type: OS::Neutron::LoadBalancer
      depends_on:
        - es_search_nodes
      properties:
        members:
        - addresses: { get_attr: [es_nodes, es_private_ip] }
        pool_id: { get_resource: LB-pool }
        protocol_port: 80

  es_network:
    type: OS::Neutron::Network
    properties:
      label: es_network
      cidr: 192.168.0.0/24

  es_search_nodes:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: es_node_count }
      resource_def:
        type: https://raw.githubusercontent.com/elastx/heat-templates/master/ElasticSearch/ElasticSearch_DataNode.yaml
        properties:
          server_flavor:    { get_param: flavor_search }
          server_hostname:  { get_param: server_hostname_search }
          ssh_keypair_name: { get_param: keyname }
          es_network_id:    { get_resource: es_network }

  es_log_nodes:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: 1
      resource_def:
        type: https://raw.githubusercontent.com/elastx/heat-templates/master/ElasticSearch/ElasticSearch_LogNode.yaml
        properties:
          server_flavor:    { get_param: flavor_log }
          server_hostname:  { get_param: server_hostname_log }
          ssh_keypair_name: { get_param: keyname }
          es_network_id:    { get_resource: es_network }

outputs:

  es_search_server_ips:
    value: { get_attr: [es_search_nodes, es_server_ip] }
    description: "Elasticsearch search Server IPs"

  es_log_server_ips:
    value: { get_attr: [es_log_nodes, es_server_ip] }
    description: "Elasticsearch log Server IPs"
